// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicRate,
  DefaultRateProps
} from "./plasmic/mr_biscuit_site/PlasmicRate";
import  UnstyledStar  from "./UnstyledStar";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface RateProps extends Omit<DefaultRateProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultRateProps altogether and have
// total control over the props for your component.
export interface RateProps extends DefaultRateProps {}

function Rate_(props: RateProps, ref: HTMLElementRefOf<"div">) {
  const [hoverValue, setHoverValue] = React.useState(0);

  return (
    <PlasmicRate
      root={{ ref }}
      children={
        [1,2,3,4,5].map((n, i) => {
        return <UnstyledStar key={i}
        // @ts-ignore
          onMouseOver={() => setHoverValue(i + 1)}
          active={i < hoverValue}
   />;
      })}
      {...props}
    />
  );
}

const UnstyledRate = React.forwardRef(Rate_);
export default UnstyledRate;
