// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicUnstyledSwitch,
  DefaultUnstyledSwitchProps
} from "./plasmic/mr_biscuit_site/PlasmicUnstyledSwitch";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface UnstyledSwitchProps extends Omit<DefaultUnstyledSwitchProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultUnstyledSwitchProps altogether and have
// total control over the props for your component.
export interface UnstyledSwitchProps extends DefaultUnstyledSwitchProps {}

function UnstyledSwitch_(
  props: UnstyledSwitchProps,
  ref: HTMLElementRefOf<"div">
) {
 
  const [isOn, setIsOn] = React.useState(false);

  return <PlasmicUnstyledSwitch frame9={{ ref }}
  onClick={() => setIsOn(!isOn)}
    on = {isOn}
  {...props} />;
}

const UnstyledSwitch = React.forwardRef(UnstyledSwitch_);
export default UnstyledSwitch;
