// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicUnstyledTabs,
  DefaultUnstyledTabsProps
} from "./plasmic/mr_biscuit_site/PlasmicUnstyledTabs";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface UnstyledTabsProps extends Omit<DefaultUnstyledTabsProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultUnstyledTabsProps altogether and have
// total control over the props for your component.
export interface UnstyledTabsProps extends DefaultUnstyledTabsProps {}

function UnstyledTabs_(props: UnstyledTabsProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicUnstyledTabs to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  const [current, setCurrent] = React.useState(0);


  return <PlasmicUnstyledTabs root={{ ref }}  first={{
    props:{
      onClick: () => setCurrent(0),
      isCurrent: current === 0
     }
  }}
  second={{
    props:{
      onClick: () => setCurrent(1),
      isCurrent: current === 1
      }
  }}  
  third={{
    props:{
      onClick: () => setCurrent(2),
      isCurrent: current === 2
      }
  }}{...props} />;
}

const UnstyledTabs = React.forwardRef(UnstyledTabs_);
export default UnstyledTabs;
