// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicUnstyledNavItem,
  DefaultUnstyledNavItemProps
} from "./plasmic/mr_biscuit_site/PlasmicUnstyledNavItem";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface UnstyledNavItemProps extends Omit<DefaultUnstyledNavItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultUnstyledNavItemProps altogether and have
// total control over the props for your component.
export interface UnstyledNavItemProps extends DefaultUnstyledNavItemProps {}

function UnstyledNavItem_(
  props: UnstyledNavItemProps,
  ref: HTMLElementRefOf<"div">
) {
  const [isExpended, setIsExpended] = React.useState(props.isGroup?true:false);

  return <PlasmicUnstyledNavItem 
  expanded={isExpended}
  par={{
    props:{
      onClick: () => {
        if (props.isGroup)
        setIsExpended(!isExpended);
      }
    }
  }}
   root={{ ref }} {...props} />;
}

const UnstyledNavItem = React.forwardRef(UnstyledNavItem_);
export default UnstyledNavItem;
