// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/mr_biscuit_site/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../../components/plasmic/pro_layout_panel_landing_pgae/PlasmicGlobalVariant__Screen";
import { PlasmicUnstyledget } from "../../components/plasmic/mr_biscuit_site/PlasmicUnstyledget";
import { useRouter } from "next/router";

function Unstyledget() {
  const [value, setValue] = React.useState("");

  return (
    <GlobalContextsProvider>
      <ph.PageParamsProvider
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicUnstyledget
          input={{
            onChange: (event) => {
              setValue(event.target.value);
            },
          }}
          download={{
            // @ts-ignore
            onClick: () => {
              const licenseKey = value;

              // the API endpoint
              const url = "https://api.lemonsqueezy.com/v1/licenses/validate";
              const productId = 'yourProductId'
              // make the POST request
              fetch(url, {
                method: "POST",
                headers: {
                  Accept: "application/json",
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({
                  license_key: licenseKey,
                }),
              })
                .then((response) => response.json())
                .then((data) => {
                  // check if the license key is valid
                  if (data.valid) {
                    // the file URL
                    const fileUrl =
                      "https://dl.dropboxusercontent.com/s/gcsbzpko9a7x6jt/UnStyled.fig";

                    // create a new a element
                    const a = document.createElement("a");

                    // set the href attribute
                    a.href = fileUrl;

                    // set the download attribute
                    a.download = "";

                    // programmatically click the a element
                    a.click();
                  } else {
                    console.log("The license key is not valid.");
                  }
                })
                .catch((error) => console.error("Error:", error));
            },
          }}
        />
      </ph.PageParamsProvider>
    </GlobalContextsProvider>
  );
}

export default Unstyledget;
