// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qDNA17RfdgsM73kkELPPxa
// Component: mk11Af_XHM
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_outline_to_single_stroke_css from "../outline_to_single_stroke/plasmic_outline_to_single_stroke.module.css"; // plasmic-import: 56iVbBJXbx9hFxysoAGHJC/projectcss
import projectcss from "../pro_layout_panel_landing_pgae/plasmic_pro_layout_panel_landing_pgae.module.css"; // plasmic-import: qDNA17RfdgsM73kkELPPxa/projectcss
import sty from "./PlasmicUnstyledSwitch.module.css"; // plasmic-import: mk11Af_XHM/css

export type PlasmicUnstyledSwitch__VariantMembers = {
  on: "on";
};

export type PlasmicUnstyledSwitch__VariantsArgs = {
  on?: SingleBooleanChoiceArg<"on">;
};

type VariantPropType = keyof PlasmicUnstyledSwitch__VariantsArgs;
export const PlasmicUnstyledSwitch__VariantProps = new Array<VariantPropType>(
  "on"
);

export type PlasmicUnstyledSwitch__ArgsType = {};
type ArgPropType = keyof PlasmicUnstyledSwitch__ArgsType;
export const PlasmicUnstyledSwitch__ArgProps = new Array<ArgPropType>();

export type PlasmicUnstyledSwitch__OverridesType = {
  frame9?: p.Flex<"div">;
  _switch?: p.Flex<"div">;
  knob?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultUnstyledSwitchProps {
  on?: SingleBooleanChoiceArg<"on">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicUnstyledSwitch__RenderFunc(props: {
  variants: PlasmicUnstyledSwitch__VariantsArgs;
  args: PlasmicUnstyledSwitch__ArgsType;
  overrides: PlasmicUnstyledSwitch__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "on",
        type: "private",
        variableType: "variant",
        initFunc: true ? ($props, $state, $ctx) => $props.on : undefined
      }
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, $props, $ctx);

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"frame9"}
      data-plasmic-override={overrides.frame9}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_outline_to_single_stroke_css.plasmic_tokens,
        sty.frame9
      )}
    >
      <div
        data-plasmic-name={"_switch"}
        data-plasmic-override={overrides._switch}
        className={classNames(projectcss.all, sty._switch, {
          [sty._switchon]: hasVariant($state, "on", "on")
        })}
      >
        <div
          data-plasmic-name={"knob"}
          data-plasmic-override={overrides.knob}
          className={classNames(projectcss.all, sty.knob, {
            [sty.knobon]: hasVariant($state, "on", "on")
          })}
        />
      </div>

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.texton]: hasVariant($state, "on", "on")
        })}
      >
        {"Switch"}
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  frame9: ["frame9", "_switch", "knob", "text"],
  _switch: ["_switch", "knob"],
  knob: ["knob"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  frame9: "div";
  _switch: "div";
  knob: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUnstyledSwitch__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUnstyledSwitch__VariantsArgs;
    args?: PlasmicUnstyledSwitch__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUnstyledSwitch__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUnstyledSwitch__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicUnstyledSwitch__ArgProps,
          internalVariantPropNames: PlasmicUnstyledSwitch__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicUnstyledSwitch__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "frame9") {
    func.displayName = "PlasmicUnstyledSwitch";
  } else {
    func.displayName = `PlasmicUnstyledSwitch.${nodeName}`;
  }
  return func;
}

export const PlasmicUnstyledSwitch = Object.assign(
  // Top-level PlasmicUnstyledSwitch renders the root element
  makeNodeComponent("frame9"),
  {
    // Helper components rendering sub-elements
    _switch: makeNodeComponent("_switch"),
    knob: makeNodeComponent("knob"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicUnstyledSwitch
    internalVariantProps: PlasmicUnstyledSwitch__VariantProps,
    internalArgProps: PlasmicUnstyledSwitch__ArgProps
  }
);

export default PlasmicUnstyledSwitch;
/* prettier-ignore-end */
