// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qDNA17RfdgsM73kkELPPxa
// Component: 1gM6u15t6Q

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import UnstyledStar from "../../UnstyledStar"; // plasmic-import: vKnKnMdjXV/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_outline_to_single_stroke_css from "../outline_to_single_stroke/plasmic_outline_to_single_stroke.module.css"; // plasmic-import: 56iVbBJXbx9hFxysoAGHJC/projectcss
import projectcss from "../pro_layout_panel_landing_pgae/plasmic_pro_layout_panel_landing_pgae.module.css"; // plasmic-import: qDNA17RfdgsM73kkELPPxa/projectcss
import sty from "./PlasmicRate.module.css"; // plasmic-import: 1gM6u15t6Q/css

export type PlasmicRate__VariantMembers = {};

export type PlasmicRate__VariantsArgs = {};
type VariantPropType = keyof PlasmicRate__VariantsArgs;
export const PlasmicRate__VariantProps = new Array<VariantPropType>();

export type PlasmicRate__ArgsType = {
  numberOfStars?: number;
  onNumberOfStarsChange?: (val: number) => void;
  onScoreChange?: (val: number) => void;
};

type ArgPropType = keyof PlasmicRate__ArgsType;
export const PlasmicRate__ArgProps = new Array<ArgPropType>(
  "numberOfStars",
  "onNumberOfStarsChange",
  "onScoreChange"
);

export type PlasmicRate__OverridesType = {
  root?: p.Flex<"div">;
  hitbox?: p.Flex<"div">;
  unstyledStar?: p.Flex<typeof UnstyledStar>;
};

export interface DefaultRateProps {
  numberOfStars?: number;
  onNumberOfStarsChange?: (val: number) => void;
  onScoreChange?: (val: number) => void;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRate__RenderFunc(props: {
  variants: PlasmicRate__VariantsArgs;
  args: PlasmicRate__ArgsType;
  overrides: PlasmicRate__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "numberOfStars",
        type: "writable",
        variableType: "number",

        valueProp: "numberOfStars",
        onChangeProp: "onNumberOfStarsChange"
      },
      {
        path: "score",
        type: "readonly",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0 as const,

        onChangeProp: "onScoreChange"
      },
      {
        path: "hover",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0 as const
      }
    ],

    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_outline_to_single_stroke_css.plasmic_tokens,
        sty.root
      )}
    >
      {true
        ? (
            (() => {
              try {
                return Array.from(
                  { length: $state.numberOfStars },
                  (_, i) => i + 1
                );
              } catch (e) {
                if (e instanceof TypeError) {
                  return [];
                }
                throw e;
              }
            })() ?? []
          ).map((currentItem, currentIndex) => (
            <div
              data-plasmic-name={"hitbox"}
              data-plasmic-override={overrides.hitbox}
              className={classNames(projectcss.all, sty.hitbox)}
              key={currentIndex}
              onClick={async event => {
                const $steps = {};
                $steps["setScore"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "HL9KwklCr",
                            componentUuid: "1gM6u15t6Q",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["score"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "HL9KwklCr",
                            componentUuid: "1gM6u15t6Q",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "HL9KwklCr",
                            componentUuid: "1gM6u15t6Q",
                            argName: "value"
                          },
                          () => $state.hover
                        )
                      };

                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "HL9KwklCr",
                          componentUuid: "1gM6u15t6Q"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            p.set(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["setScore"] === "object" &&
                  typeof $steps["setScore"].then === "function"
                ) {
                  $steps["setScore"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "HL9KwklCr",
                      componentUuid: "1gM6u15t6Q"
                    },
                    $steps["setScore"]
                  );
                }
              }}
              onMouseOver={async event => {
                const $steps = {};
                $steps["setHover"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "uWkAFFthh",
                            componentUuid: "1gM6u15t6Q",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["hover"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "uWkAFFthh",
                            componentUuid: "1gM6u15t6Q",
                            argName: "operation"
                          },
                          () => 0
                        ),
                        value: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "uWkAFFthh",
                            componentUuid: "1gM6u15t6Q",
                            argName: "value"
                          },
                          () => currentIndex
                        )
                      };

                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "uWkAFFthh",
                          componentUuid: "1gM6u15t6Q"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            p.set(objRoot, variablePath, value);
                            return value;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["setHover"] === "object" &&
                  typeof $steps["setHover"].then === "function"
                ) {
                  $steps["setHover"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "uWkAFFthh",
                      componentUuid: "1gM6u15t6Q"
                    },
                    $steps["setHover"]
                  );
                }
              }}
            >
              <UnstyledStar
                data-plasmic-name={"unstyledStar"}
                data-plasmic-override={overrides.unstyledStar}
                active={
                  $state.hover >= currentIndex || $state.score >= currentIndex
                }
                className={classNames("__wab_instance", sty.unstyledStar)}
              />
            </div>
          ))
        : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "hitbox", "unstyledStar"],
  hitbox: ["hitbox", "unstyledStar"],
  unstyledStar: ["unstyledStar"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  hitbox: "div";
  unstyledStar: typeof UnstyledStar;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRate__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRate__VariantsArgs;
    args?: PlasmicRate__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRate__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRate__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRate__ArgProps,
          internalVariantPropNames: PlasmicRate__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRate__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRate";
  } else {
    func.displayName = `PlasmicRate.${nodeName}`;
  }
  return func;
}

export const PlasmicRate = Object.assign(
  // Top-level PlasmicRate renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    hitbox: makeNodeComponent("hitbox"),
    unstyledStar: makeNodeComponent("unstyledStar"),

    // Metadata about props expected for PlasmicRate
    internalVariantProps: PlasmicRate__VariantProps,
    internalArgProps: PlasmicRate__ArgProps
  }
);

export default PlasmicRate;
/* prettier-ignore-end */
